cads/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

saprgram/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('authentication.urls', namespace='authentication')),
    path('', include('saprgramapp.urls', namespace='saprgramapp'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

saprgramapp/urls.py
from django.urls import path

from .views import *

app_name = 'saprgramapp'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('registration/', user_registration_view, name='registration'),
    path('login/', user_login_view, name='login'),
    path('user/', user_page_view, name='user_page'),
    path('user/edit_page', user_edit_page, name='edit_page'),
    path('ourTeam/', our_team_view, name='ourTeam'),
    path('user/addPublication', add_publication_view, name='add_pub'),
    path('tape/', tape_view, name='tape')
]

taskmanager/taskmanager/urls.py
from django.contrib import admin
from django.urls import path
from home.views import Home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', Home.as_view())
]

saprgramapp/models.py
from django.db import models
from authentication.models import User


def user_directory_path(instance, filename):
    return 'photos/publications/user_{0}/{1}'.format(instance.user.id, filename)


class Publication(models.Model):
    user_photo = models.ImageField(upload_to=user_directory_path)  # Photo
    data = models.TextField(blank=True)  # Description under the photo
    date = models.DateTimeField(auto_now_add=True)  # Date of creation
    user = models.ForeignKey(User, on_delete=models.PROTECT, null=True, blank=True, default=None)

    class Meta:
        ordering = ['user']
        verbose_name = 'Publication'  # Change table name
        verbose_name_plural = 'Publications'

    def __str__(self):
        return str(self.user)


class Comments(models.Model):
    comment = models.TextField()  # Text of the comment
    # ID of the post that is commented by any user
    post = models.ForeignKey(Publication, on_delete=models.PROTECT, null=True, blank=True)
    # ID of user who made comments
    commenter = models.ForeignKey(User, on_delete=models.PROTECT, null=True, blank=True)

    class Meta:
        ordering = ['post']
        verbose_name = 'Comment'  # Change table name
        verbose_name_plural = 'Comments'

saprgramapp/forms.py
from django.forms import ModelForm, TextInput, FileInput

from authentication.models import User
from .models import Publication


class RegistrationForm(ModelForm):
    class Meta:
        model = User
        fields = ['username', 'password', 'email']
        widgets = {
            'username': TextInput(attrs={
                'id': 'username',
                'type': 'username',
                'placeholder': 'Enter username'
            }),
            'password': TextInput(attrs={
                'id': 'password',
                'type': 'password',
                'placeholder': 'Enter password'
            }),
            'email': TextInput(attrs={
                'id': 'email',
                'type': 'email',
                'placeholder': 'Enter email'
            })
        }


class LoginForm(ModelForm):
    class Meta:
        model = User
        fields = ['email', 'password']
        widgets = {
            'email': TextInput(attrs={
                'id': 'email',
                'type': 'email',
                'placeholder': 'Enter email'
            }),
            'password': TextInput(attrs={
                'id': 'password',
                'type': 'password',
                'placeholder': 'Enter password'
            })
        }


class UserEditForm(ModelForm):
    class Meta:
        model = User
        fields = ['avatar_photo', 'email', 'github', 'instagram', 'user_course', 'user_description']
        widgets = {
            'avatar_photo': FileInput(attrs={
                'type': 'file',
            }),
            'email': TextInput(attrs={
                'type': 'text',
                'class': 'form-control',
                'placeholder': 'Enter your email',
            }),
            'github': TextInput(attrs={
                'type': 'text',
                'class': 'form-control',
                'placeholder': 'Enter your github username '
            }),
            'instagram': TextInput(attrs={
                'type': 'text',
                'class': 'form-control',
                'placeholder': 'Enter your instagram'
            }),
            'user_course': TextInput(attrs={
                'type': 'text',
                'class': 'form-control',
                'placeholder': 'Enter your course'
            }),
            'user_description': TextInput(attrs={
                'type': 'text',
                'class': 'form-control',
                'placeholder': 'Enter description of your profile'
            }),
        }


class AddingPublicationForm(ModelForm):
    class Meta:
        model = Publication
        fields = ['user_photo', 'data']
        widgets = {
            'user_photo': FileInput(attrs={
                'id': 'avatar',
                'type': 'file',
                'class': 'form-control col-md-3 ml-5 pl-5',
                'placeholder': 'Upload photo'
            }),
            'data': TextInput(attrs={
                'id': 'pub_data',
                'class': 'form-control col-md-3 ml-5 pl-5',
                'type': 'text'
            })
        }

saprgramapp/views.py
from django.views.decorators.csrf import csrf_protect
from django.views.generic import TemplateView
from django.shortcuts import redirect, render, get_object_or_404
from django.conf import settings
from .models import Publication, Comments
from saprgram.settings import BASE_DIR
from .forms import *
import os
import jwt
import requests


class HomeView(TemplateView):
    template_name = 'home/index.html'


def user_registration_view(request):
    form = RegistrationForm()
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if not form.is_valid():
            return render(request, 'authentication/user_registration.html', {'form': form})

        email = request.POST.get('email')
        username = request.POST.get('username')
        password = request.POST.get('password')

        registration_request = {
            'user': {
                'email': email,
                'username': username,
                'password': password,
            }
        }

        try:
            response = requests.post('http://localhost:8000/api/user/register/', json=registration_request)
            response.raise_for_status()
        except requests.exceptions.HTTPError:
            pass # TODO: Handle API errors.

        if 'errors' in response.json():
            pass # TODO: Handle signup errors.
        else:
            return redirect('saprgramapp:login')

    return render(request, 'authentication/user_registration.html', {'form': form})


def user_login_view(request):
    form = LoginForm()
    context = {
        'form': form
    }

    if request.method == 'POST':
        email = request.POST.get('email')
        password = request.POST.get('password')

        login_request = {
             'user': {
                 'email': email,
                 'password': password
             }
         }

        try:
            response = requests.post('http://localhost:8000/api/user/login/', json=login_request)
            response.raise_for_status()
        except requests.exceptions.HTTPError:
            pass # TODO: Handle API errors.

        json = response.json()
        if 'errors' in json:
            context['form'].login_errors = 'Invalid email or password.'
        else:
            response = redirect('/user/')
            response.set_cookie('JWT_TOKEN', json['user']['token'])
            os.chdir(str(BASE_DIR) + f'\\media\\photos\\publications')
            user_dir = f'user_{User.objects.get(email=email).id}'
            if not os.path.exists(user_dir):
                os.mkdir(user_dir)
            return response

    return render(request, 'authentication/user_login.html', context)


def user_page_view(request):
    public = jwt.decode(request.COOKIES['JWT_TOKEN'][2:-1], settings.SECRET_KEY, algorithms=["HS256"])
    user_data = User.objects.get(pk=public['id'])
    user_publications = Publication.objects.filter(user_id=user_data.pk)

    user_data = User.objects.get(pk=public['id'])
    if public['id'] == user_data.id:
        context = {
            'user_data': user_data,
            'user_posts': user_publications,
            'logged': 1
        }

    else:
        context = {
            'user_data': user_data,
            'user_posts': user_publications,
            'logged': 0
        }
    print(context['logged'])
    return render(request, 'userpage/user_page.html', context)


@csrf_protect
def add_publication_view(request):
    user_id = jwt.decode(request.COOKIES['JWT_TOKEN'][2:-1], settings.SECRET_KEY, algorithms=["HS256"])['id']
    form = AddingPublicationForm()
    if request.method == 'POST':
        form = AddingPublicationForm(request.POST, request.FILES)

        os.chdir(str(BASE_DIR) + f'\\media\\photos\\publications\\user_{user_id}')

        if form.is_valid() and not os.path.exists(str(request.FILES['user_photo'])):
            new_pub = form.save(commit=False)
            new_pub.user_id = user_id
            new_pub.save()
    context = {'form': form}
    return render(request, 'userpage/Adding_Publications.html', context)


def tape_view(request):
    posts = Publication.objects.all()[::-1]

    context = {
        'posts': posts
    }
    return render(request, 'tape/tape.html', context)


def user_edit_page(request):
    public = jwt.decode(request.COOKIES['JWT_TOKEN'][2:-1], settings.SECRET_KEY, algorithms=["HS256"])
    user_data = User.objects.get(pk=public['id'])
    form = UserEditForm()
    if request.method == 'POST':

        os.chdir(str(BASE_DIR) + '\\media\\photos\\avatar')

        user_data = get_object_or_404(User, id=public['id'])
        form = UserEditForm(data=request.POST, files=request.FILES, instance=user_data)

        if form.is_valid():
            if request.FILES:
                photo = request.FILES['avatar_photo']
                if not os.path.exists(str(photo)):
                    form.save(commit=True)
            else:

                form.save(commit=True)
    context = {
       'user_data': user_data,
        'form': form
    }
    return render(request, 'userpage/Editting_page.html', context)


def our_team_view(request):
    return render(request, 'home/ourTeam.html')


def base_view(request):
    public = jwt.decode(request.COOKIES['JWT_TOKEN'][2:-1], settings.SECRET_KEY, algorithms=["HS256"])
    username = User.objects.get(pk=public['id'])
    context = {'username': username}
    return render(request, 'base.html', context)

saprgramapp/templates/userpage/Adding_Publications.html
{% load static %}
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet">
    <div class="container ">


    <form enctype="multipart/form-data" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="shine-button">Submit</button>
    </form>
    </div>

saprgramapp/templates/userpage/Editting_page.html
{% extends 'base.html' %}

{% block body %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet">
    <div class="test">
<div class="container">
    <form enctype="multipart/form-data" method="POST" id="form">
        {% csrf_token %}
    <div class="main-body">
        <div class="row">
            <div class="col-lg-4">
                <div class="card">
                    <div class="card-body">
                        <div class="d-flex flex-column align-items-center text-center">
                            <img src="{{ user_data.avatar_photo.url }}" alt="Admin" class="rounded-circle" width="150">
                            <div class="mt-3">
                                <h4>{{ user_data.username }}</h4>
                                <p class="text-secondary mb-1">{{user_data.user_description}}</p>

                                    {{ form.avatar_photo }}

                            </div>
                        </div>

                        <hr class="my-4">

                            <ul class="list-group list-group-flush">
                            <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
                                <h6 class="mb-0"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-github me-2 icon-inline"><path d="M9 19c-5 1.5-5-2.5-7-3m14 6v-3.87a3.37 3.37 0 0 0-.94-2.61c3.14-.35 6.44-1.54 6.44-7A5.44 5.44 0 0 0 20 4.77 5.07 5.07 0 0 0 19.91 1S18.73.65 16 2.48a13.38 13.38 0 0 0-7 0C6.27.65 5.09 1 5.09 1A5.07 5.07 0 0 0 5 4.77a5.44 5.44 0 0 0-1.5 3.78c0 5.42 3.3 6.61 6.44 7A3.37 3.37 0 0 0 9 18.13V22"></path></svg>Github</h6>
                                {{form.github}}
                            </li>
                            <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
                                <h6 class="mb-0"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-instagram me-2 icon-inline text-danger"><rect x="2" y="2" width="20" height="20" rx="5" ry="5"></rect><path d="M16 11.37A4 4 0 1 1 12.63 8 4 4 0 0 1 16 11.37z"></path><line x1="17.5" y1="6.5" x2="17.51" y2="6.5"></line></svg>Instagram</h6>
                                {{form.instagram}}
                            </li>

                        </ul>
                    </div>
                </div>
            </div>
            <div class="col-lg-8">
                <div class="card">
                    <div class="card-body">

                        <div class="row mb-3">
                            <div class="col-sm-3">
                                <h6 class="mb-0">Course</h6>
                            </div>
                            <div class="col-sm-9 text-secondary">
                                {{form.user_course}}
                            </div>
                        </div>
                        <div class="row mb-3">
                            <div class="col-sm-3">
                                <h6 class="mb-0">Email</h6>
                            </div>
                            <div class="col-sm-9 text-secondary">
                                {{form.email}}
                            </div>
                        </div>
                        <div class="row mb-3">
                            <div class="col-sm-3">
                                <h6 class="mb-0">Description</h6>
                            </div>
                            <div class="col-sm-9 text-secondary">
                            {{ form.user_description }}
                            </div>
                        </div>
                        <div class="row mb-3">
                            <div class="col-sm-3">
                                <input class="btn btn-info" type="submit">
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>
        </form>
    </div>
</div>
{% endblock %}

saprgramapp/templates/userpage/user_page.html
{% extends 'base.html' %}
{%load static%}


{% block body %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet">
    <div class="container">
        <div class="main-body">
            <div class="test">
            <div class="row gutters-sm">
                <div class="col-md-4 mb-3">
                    <div class="card">
                        <div class="card-body">
                            <div class="d-flex flex-column align-items-center text-center">
                                <img src="{{ user_data.avatar_photo.url }}" alt="Admin" class="rounded-circle" width="150">
                                <div class="mt-3">
                                    <h4>{{ user_data.login}}</h4>
                                    <p class="text-secondary mb-1">{{user_data.user_description}}</p>
                                    <button class="btn btn-primary">Follow</button>
                                    <button class="btn btn-outline-primary">Message</button>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="card mt-3">
                        <ul class="list-group list-group-flush">
                            <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
                                <h6 class="mb-0"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-github mr-2 icon-inline"><path d="M9 19c-5 1.5-5-2.5-7-3m14 6v-3.87a3.37 3.37 0 0 0-.94-2.61c3.14-.35 6.44-1.54 6.44-7A5.44 5.44 0 0 0 20 4.77 5.07 5.07 0 0 0 19.91 1S18.73.65 16 2.48a13.38 13.38 0 0 0-7 0C6.27.65 5.09 1 5.09 1A5.07 5.07 0 0 0 5 4.77a5.44 5.44 0 0 0-1.5 3.78c0 5.42 3.3 6.61 6.44 7A3.37 3.37 0 0 0 9 18.13V22"></path></svg>Github</h6>
                                <span class="text-secondary">{{ user_data.github }}</span>
                            </li>
                            <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
                                <h6 class="mb-0"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-instagram mr-2 icon-inline text-danger"><rect x="2" y="2" width="20" height="20" rx="5" ry="5"></rect><path d="M16 11.37A4 4 0 1 1 12.63 8 4 4 0 0 1 16 11.37z"></path><line x1="17.5" y1="6.5" x2="17.51" y2="6.5"></line></svg>Instagram</h6>
                                <span class="text-secondary">{{ user_data.instagram }}</span>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="col-md-8">
                    <div class="card mb-3">
                        <div class="card-body">
                            <div class="row">
                                <div class="col-sm-3">
                                    <h6 class="mb-0">Course</h6>
                                </div>
                                <div class="col-sm-9 text-secondary">
                                    {{ user_data.user_course }}
                                </div>
                            </div>
                            <hr>
                            <div class="row">
                                <div class="col-sm-3">
                                    <h6 class="mb-0">Email</h6>
                                </div>
                                <div class="col-sm-9 text-secondary">
                                    {{user_data.email}}
                                </div>
                            </div>
                            <hr>
                            <div class="row">
                                {% if logged == 1 %}
                                <div class="col-sm-12">
                                    <a class="btn btn-info " target="__blank" href="{% url 'saprgramapp:edit_page' %}">Edit</a>
                                </div>
                                {% else %}
                                {% endif %}
                            </div>
                        </div>
                    </div>

                    {% if logged == 1 %}
                    <div class="col-sm-12">
                        <a class="btn btn-info " target="__blank" href="{% url 'saprgramapp:add_pub' %}">Add</a>
                    </div>
                    {% else %}
                    {% endif %}
                    {% for pub in user_posts %}
                            <img src="{{ pub.user_photo.url }}" class="img-fluid ml-2 mb-2" alt="" height="300px" width="300px">
                    {% endfor %}
                </div>
            </div>
            </div>
        </div>
    </div>
{% endblock %}